# Generated by Django 4.1.2 on 2022-10-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JonsBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default="Jon's Blog", max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Jon's Blog", max_length=255),
        ),
    ]
