# Generated by Django 4.1.2 on 2022-11-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JonsBlog', '0005_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
