# Generated by Django 4.1.2 on 2022-11-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JonsBlog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to see the blog post.', max_length=255),
        ),
    ]
